import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Anton, Bonheur_Royale } from "next/font/google";
import Footer from "@/components/containers/footer/Footer";
import Navbar from "@/components/containers/navbar/Navbar";
import StarBackground from "@/components/ui/starBackground";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});

const anton = Anton({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-anton",
});

const bonheur_royal = Bonheur_Royale({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bonheur_royal",
});

export const metadata: Metadata = {
  title: "Khusnul Ulum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${montserrat.className} ${anton.variable} ${bonheur_royal.variable} antialiased`}
      >
        <StarBackground />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
